<a href="https://colab.research.google.com/github/pacomm5/Plantillas/blob/main/plantilla%20preprocesado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clonamos el repositorio para obtener los dataSet

In [1]:
#!git clone https://github.com/joanby/machinelearning-az.git
! git clone https://github.com/pacomm5/machinelearning-az # de esta manera lo que hacemos es acceder a todos los datasets mios de github. en este caso de marchine learning de la a a la z

Cloning into 'machinelearning-az'...
remote: Enumerating objects: 10541, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 10541 (delta 25), reused 0 (delta 0), pack-reused 10505
Receiving objects: 100% (10541/10541), 311.58 MiB | 22.41 MiB/s, done.
Resolving deltas: 100% (245/245), done.
Checking out files: 100% (10250/10250), done.


# Damos acceso a nuestro Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Test it

In [3]:
!ls '/content/machinelearning-az' 

'additional materials'	 LICENSE		    README.md
 datasets		 machinelearning-az.Rproj


# Google colab tools

In [4]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive
import sklearn
from sklearn.impute import SimpleImputer

# Plantilla de Pre Procesado

## Cómo importar las librerías


In [ ]:
import numpy as np # este para matemáticas. 
import matplotlib.pyplot as plt # este para gráficos
import pandas as pd # perfecta carga, manipular.... datos. 

## Importar el data set


In [ ]:
dataset = pd.read_csv('/content/machinelearning-az/datasets/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data.csv')

X = dataset.iloc[:, :-1].values # con esto quitamos la variable dependiente que es purchased. poenmos .values para que nos saque los valores. 
y = dataset.iloc[:, 3].values # aqui dejamos la variable  independientes. 


' escribiendo código\nX = dataset.iloc[:,:-1].values\ny = dataset.iloc[:, 3]'

después de realizar esto tendremos las variables independientes en X y la variable dependiente en y. ambos son arrays

## PROBLEMAS DE FORMATO AL IMPORTAR

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/TRABAJO MASTER/df_est_total.csv", sep="|", encoding="ISO-8859-1")

## VER LOS NOMBRES DE LAS COLUMNAS QUE TIENE

In [ ]:
df1.columns

## ver el tipo de formato de las variables etc...

In [ ]:
df2.types con esto vemos el tipo de las variables. 

In [ ]:
df2.describe() # con esto vemos contar, media minimoo max quartiles. 

In [ ]:
df2.isnull().sum() #para ver los nan

In [ ]:
df.shape # con esto vemos la forma de dataframe, también lo podemos hacer con un array. 

## CONVERTIR EL TIPO DE VARIABLES. 

In [ ]:
df['id_cl']=df['id_cl'].apply(str)
df["anno"] = df["anno"].apply(str)
df["mes"] = df["mes"].apply(str)
df["cod_sector"] = df["cod_sector"].apply(str)
df["provincia"] = df["provincia"].apply(str)

In [ ]:
# con esto creamos la columna de fecha desde varias columnas. 


df["Fecha"] = df["anno"] + "/" + df["mes"] 
#data["Fecha"] = data["anno"] + "/" + data["mes"] + "/" + "01"
df.Fecha = pd.to_datetime(df.Fecha, dayfirst = True)

## RENOMBRAR VARIABLES. 

In [ ]:
df_gr_cl = df_gr_cl.rename(columns={'importe2':'imp2_tot_cl'}).reset_index()

##RESET INDEX

In [ ]:
df3.reset_index(inplace=True, drop=True)
df3.head()

## FILTRAR DATASET

In [ ]:
dataset.iloc[:, 0:3].head() # esto no vale para nada es para ver como filtrar un data set. 
# NO HEMOS ASIGNADO VARIABLE POR LO TANTO NO CAMBIA NADA SOLO SE VISUALIZA

también lo podemos hacer así. 

In [ ]:
df2 = df1[["id_cl", "Fecha"]] # vamos introduciendo todas las columnas que queramos. 
# se colocarán en el orden que las pongamos. 

### FILTRAR POR FECHA

In [ ]:
split_date = pd.datetime(2018,12,1)
df_fecha_cl = df_fecha_cl0.loc[df_fecha_cl0.index <= split_date].copy()
df_fecha_cl.head(30)
# con esto filtramos por fecha menor o igual al split_date

### filtrar por fila

In [ ]:
df["nombre de la columna"]=="nombre de lo que queremos filtrar "
df["nombre de la columna"]=="300" # filtro por un valor. 

In [ ]:
df_mask = df2[(df2.PIB >0) & (df2.cotiz_empleadores>0)] # aqui estamos filtrando por dos condiciones.
df_mask = df2[(df2.PIB >0)]# aqui por una condición

## AGRUPAR POR UNA VARIABLE. 

In [ ]:
df_gr_cl=pd.DataFrame(df_fecha.groupby('id_cl')['importe2'].sum())

In [ ]:
gr_activ=df_fecha.groupby(['rama_actividad','desc_actividad']).count() # AGRUPAR Y CONTAR 

In [ ]:
df5 = df3.groupby(["Fecha", "desc_actividad"]).agg({"importe2":["sum"], "PIB":["mean"], "cotiz_empleadores":["mean"]}).reset_index()
df5.head()
# agrupar por varias variables y asignandoles una función diferente. 
# ejemplo el importe2 lo sumamos, el importe hacemos la media, y la cotizacion hacemos la media. 

# OJO ESTO GENERA UN PROBLEMA YA QUE LAS COLUMNAS SE CONVIERTEN EN MULTIINDEX
# PARA QUITARLO HACEMOS ESTO
df5.columns = ["Fecha", "desc_actividad", "importe2", "PIB", "cotiz_empleadores"] 
# lo que hacemos es renombrar las columnas y se quita. 

## MOVER UNA COLUMNA DE POSICION

In [ ]:
# si por ejemplo tenemos un df = con las columnas a,b,c,d,e,f
# y queremos monver la columna b al último lugar lo hacemos así. 
# df= df[["a", "c", "d", "e", "f", "a"]]
# de esta manera la colocaremos al final. muy util para separa variables independientes de las independientes. 
# servirça para filtrar y tambien para recolocar las filas. 

In [ ]:
# otra manera sería así. 
# df.reindex(columns=["a", "c", "d", "e", "f", "a"])

## INTRODUCIR UNA NUEVA COLUMNA

In [ ]:
# si queremos meter una nueva columna se hace así. 
# df.insert(0, "nombre de la columna", df.mean(1)) en este caso hemos insertado una nueva columna 
# en la posición 0, y el valor que hemos metido es la media de toda la fila.

## UNIMOS DOS DATASET

In [ ]:
# si queremos unir dos dataset se hace así. 
# dataset4 = pd.concat([dataset2,dataset3], axis=1, join="inner")

### UNIR DOS DATASET CON CLAVE PRIMARIA

In [ ]:
df_fecha_tot=pd.merge(df_fecha,df_cl_tot,left_on=['id_cl','Fecha'], right_on=['id_cl','Fecha'],how='left')

## DATOS FALTANTES VALORES NAN

con los datos faltantes podemos hacer muchas cosas. eliminar la columna, la fila, rellenar con un valor, rellenar con la media, con el valor anterior, posterior etc...

In [ ]:
df.isnull().sum().sort_value(ascending = False) # con esto sacamos el resumen y ordenador de mayor a menor
# si queremos ver el porcentaje lo hacemos de la siguiente manera. 
percent = (df.isnull().sum() / df.isnull().count().sort_values(ascending = False))

In [ ]:
df.fillna(0) # con esto rellenamos los valores faltantes a 0

In [ ]:
from pandas.core import missing
# VAMOS A REMPLAZAR POR LA MEDIA. 
# recordatorio axis = 0 es media de columna si fuera 1 sería por linea. 
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean", verbose=0) # asi lo que hacemos es convertir los valores nan por la media de la columna. 
imputer = imputer.fit(X[:,1:3]) # el objeto que queremos arreglar es la X, le decimos que todas las filas, y acotamos las columnas a las que se lo queremos hacer. recordar ponemos 3 porque coge siempre la anterior. 
# en python la primera columna es 0 y cuando acotamos la última que cogemos siempre ponemos un numero más. 
X[:, 1:3] = imputer.transform(X[:,1:3]) # asi es como definitivamente lo hacemos. 
 
"""
Escribimos código
imputer = SimpleImputer(missing_values= np.nan, strategy= "mean", verbose=0)
imputer = imputer.fit(X[:,1:3])
x[:,1:3] = imputer.transform[X[:,1:3]] """
X # veremos debajo que ha quedado sustituido.

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## DATOS CATEGORICOS TRADUCIR A NUMEROS. 

lo que vamos a hacer estraducir los datos categoriocs a números. ejemplo españa 1, alemania 2 ...

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

hay dos maneras de hacerlo. la primera lo pone como numeros en una columna. pero eso puede dar luegar a que los entienda como ordinales. la otra manera es ponerlos en columnas.

In [ ]:
# OJOO NO HAY QUE CODIFICARLO ASÍ PORQUE TE LO PONE EN UNA UNICA COLUMNA Y LO PUEDE CONSIDERAR ORDINAL
#labelencoder_X = LabelEncoder() # este es el constructor 
#X[:, 0] = labelencoder_X.fit_transform(X[:, 0]) # sabemos que 0 es la columna de país. 
#X[:,0] # como podemos ver la primera que era Francia la ha codificado como 0, la seguna españa 2, la tercera alemania 1....

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [ ]:
#X # aqui vemos como lo ha cambiado. el problema que al codificarlo así, va a entender que 0 es menor que 1. es decir la va a considerar como ordinal.....
# ahora debajo vamos a ver las variables dummy. 

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

esta es la segunda manera con la que lo que hace es ponerlo en columnas. 

In [ ]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],    # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                         # Leave the rest of the columns untouched
)


In [ ]:
X = ct.fit_transform(X)
X # vemos que aquí ya lo ha transformado, p

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

aqui lo hacemo de una vez este segundo metodo

In [ ]:
"""from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import make_column_transformer
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = make_column_transformer((OneHotEncoder(), [3]), remainder = "passthrough")
X = onehotencoder.fit_transform(X)"""

###EVITAR LA TRAS DE LAS VARIABLES FICTICIAS. 

In [ ]:
X = X[:, 1:] # con esto lo que hacemos es eliminar una ya que cuando dos den 0 será la tercera. 

## Dividir el data set en conjunto de entrenamiento y conjunto de testing


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) # random_state es la semilla. 

## TRANSFORMAR UN ARRAY EN DATAFRAME

In [ ]:
result = pd.DataFrame({'California': X[:, 0], 'Florida': X[:, 1],'New York': X[:, 2]})
#result = pd.DataFrame({'Column1': X[:, 0], 'Column2': X[:, 1],'Column3': X[:, 2]})
# esto entiendo es para convertir el array en un dataframe. 

## Escalado de variables

### StandarScaler

In [ ]:
from sklearn.preprocessing import StandardScaler # esta tenderá a crear una campana de gauss. aglutina valores en torno a la media. 
# la normalización, transforma en 0 y 1

In [ ]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test) # aqui le decimos que escale igual que en X_train. 
# la pregunta sería ¿tenemos que escalar las variables dummy?.  AQUI SI LO HACEMOS. 

In [ ]:
X_train # como vemos al haberlo transformados el 0 1 de los paises se ha convertido en numeros diferentes. 

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [ ]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])