<a href="https://colab.research.google.com/github/pacomm5/Plantillas/blob/main/regresi%C3%B3n_polinomica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Regresión polinomial. es como la simple pero elevada pero vemos que tiene una tendencia exponencial. no es lineal

# Clonamos el repositorio para obtener los dataSet

In [1]:
#!git clone https://github.com/joanby/machinelearning-az.git
! git clone https://github.com/pacomm5/machinelearning-az

fatal: destination path 'machinelearning-az' already exists and is not an empty directory.


# Damos acceso a nuestro Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Test it

In [4]:
!ls '/content/drive/My Drive' 

'2019_097 Audi Service News - Campaña Modelo de predicción de abandono.msg'
'31 de agosto.xlsx'
'Acuerdos_Preformance meeting_Junio17- Jarmauto_v1.pdf'
 C3942BF2-8A67-4F4F-B37D-7656F1E356DD.doc
'Chalet Loranca.doc'
 characters-simpsons.csv
'Colab Notebooks'
'Copia de clase20220120Mborrajo.mp4'
'Copia de Clasificacion-1.ipynb'
'Copia de Clasificación-2.ipynb'
'Copia de Clustering.ipynb'
'Copia de EDA-Feature_Selection.ipynb'
'Copia de Feature_Engineering.ipynb'
'Copia de Regression.ipynb'
'Copia de requirements.txt'
'Copy of 1. Les verbes en -ER-Rosa (1).pdf'
'Copy of 1. Les verbes en -ER-Rosa.pdf'
 curriculum.doc
 curriculum.doc.gdoc
'Escaneado 21 ago 2016 3.21.pdf'
 HS3ABA.ZIP
 HS4EF4.ZIP
'HS4EF4.ZIP (Unzipped Files)'
 HS6.ZIP
 HS7859.ZIP
'HS7859.ZIP (Unzipped Files)'
 HSA151.ZIP
 HSA9B3.ZIP
 HSD86A.ZIP
'HSD86A.ZIP (Unzipped Files)'
 Inversión.gsheet
 jarmauto
 JARMAUTO2
 Justificante.pdf
 kaggle
 libros
'parque jarmauto (1).docx.gdoc'
'parque jarmauto.docx'
'parque jarmauto.docx.gdoc

#Google colab tools

In [3]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

#Instalar dependendias

In [4]:
!pip install sklearn

# Regresión polinómica


# Cómo importar las librerías


In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [6]:
dataset = pd.read_csv('/content/machinelearning-az/datasets/Part 2 - Regression/Section 6 - Polynomial Regression/Position_Salaries.csv')
X = dataset.iloc[:, 1:2].values
y = dataset.iloc[:, 2].values


In [7]:
dataset.head() # tenemos diferentes niveles y la otra variable a predicir es el salario
# tenemos una regressión multiple.
# solo vamos a utilizar level y salary. level la independiente y salary la dependiente. 

Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [8]:
print(X.shape) # esto es una matriz, tiene dos dimensiones. (10,1)
print(y.shape) # esto es un vector.

(10, 1)
(10,)


In [9]:
X # este es el nivel

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [10]:
y # esta es la variable a predecir que el es el sueldo

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

# Dividir el data set en conjunto de entrenamiento y conjunto de testing. NO TIENE SENTIDO HACERLO PORQUE TENEMOS MUY POCOS DATOS


In [ ]:
"""from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)"""

# Escalado de variables

In [ ]:
"""from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)"""

# Ajustar la regresión lineal con el dataset

In [11]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression() # no necesitamos meter ningún argumento. 
lin_reg.fit(X, y) # aquí ajustamos. le metemos toda la X e y

LinearRegression()

In [12]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [13]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [14]:
from sklearn.preprocessing import PolynomialFeatures

In [15]:
poly_reg = PolynomialFeatures(degree = 4) # aqui transformamos la X en polinomial. le metemos el argumento degree igual a 4
# el grado por defecto es 2 ( en ese caso calcularía solo los cuadrados). 
X_poly = poly_reg.fit_transform(X) # aqui lo ajustamos la matriz original.
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y)

LinearRegression()

In [16]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [17]:
X_poly # vemos que nos genera la columna de unos, y luego nos pone cuatro columnas. 
# le hemos dicho grado 4

array([[1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 2.000e+00, 4.000e+00, 8.000e+00, 1.600e+01],
       [1.000e+00, 3.000e+00, 9.000e+00, 2.700e+01, 8.100e+01],
       [1.000e+00, 4.000e+00, 1.600e+01, 6.400e+01, 2.560e+02],
       [1.000e+00, 5.000e+00, 2.500e+01, 1.250e+02, 6.250e+02],
       [1.000e+00, 6.000e+00, 3.600e+01, 2.160e+02, 1.296e+03],
       [1.000e+00, 7.000e+00, 4.900e+01, 3.430e+02, 2.401e+03],
       [1.000e+00, 8.000e+00, 6.400e+01, 5.120e+02, 4.096e+03],
       [1.000e+00, 9.000e+00, 8.100e+01, 7.290e+02, 6.561e+03],
       [1.000e+00, 1.000e+01, 1.000e+02, 1.000e+03, 1.000e+04]])

In [19]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

# Visualización de los resultados del Modelo Lineal

In [ ]:
plt.scatter(X, y, color = "red")
plt.plot(X, lin_reg.predict(X), color = "blue")
plt.title("Modelo de Regresión Lineal")
plt.xlabel("Posición del empleado")
plt.ylabel("Sueldo (en $)")
plt.show()

# Visualización de los resultados del Modelo Polinómico

In [ ]:
X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color = "red")
plt.plot(X_grid, lin_reg_2.predict(poly_reg.fit_transform(X_grid)), color = "blue")
plt.title("Modelo de Regresión Polinómica")
plt.xlabel("Posición del empleado")
plt.ylabel("Sueldo (en $)")
plt.show()

# Predicción de nuestros modelos
# Se ha añadido la sintaxis de doble corchete necesaria para hacer la predicción en las últimas versiones de Python (3.7+)

In [ ]:
lin_reg.predict([[6.5]])
lin_reg_2.predict(poly_reg.fit_transform([[6.5]]))